# Variables #
air-bin = ~/Downloads/air14_sdk_mac/bin

VERSION = 1.0.1

SWC = sessionm-actionscript-$(VERSION).swc

XCODE = sessionm-ios/src/xcode/sessionm-ios.xcodeproj/project.xcworkspace

CERTIFICATE = src/main/flex/Certificates.p12

PROVISION = src/main/flex/SessionM_AIR_Example_Profile.mobileprovision